ALTER TABLE "installers" ADD COLUMN "signature_sha256" text;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "channel" text;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "installer_locale" text;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "minimum_os_version" text;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "nested_installer_type" text;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "upgrade_behavior" text;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "package_family_name" text;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "product_code" text;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "release_date" text;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "elevation_requirement" text;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "repair_behavior" text;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "installer_aborts_terminal" boolean;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "install_location_required" boolean;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "require_explicit_upgrade" boolean;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "display_install_warnings" boolean;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "download_command_prohibited" boolean;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "archive_binaries_depend_on_path" boolean;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "platform" text[];--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "install_modes" text[];--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "commands" text[];--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "protocols" text[];--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "file_extensions" text[];--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "capabilities" text[];--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "restricted_capabilities" text[];--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "unsupported_os_architectures" text[];--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "unsupported_arguments" text[];--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "installer_success_codes" integer[];--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "apps_and_features_entries" jsonb;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "dependencies" jsonb;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "nested_installer_files" jsonb;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "expected_return_codes" jsonb;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "markets" jsonb;--> statement-breakpoint
ALTER TABLE "installers" ADD COLUMN "installation_metadata" jsonb;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "publisher_url" text;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "publisher_support_url" text;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "privacy_url" text;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "author" text;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "package_url" text;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "license_url" text;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "copyright" text;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "copyright_url" text;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "description" text;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "release_notes" text;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "release_notes_url" text;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "purchase_url" text;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "installation_notes" text;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "agreements" jsonb;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "documentations" jsonb;--> statement-breakpoint
ALTER TABLE "locales" ADD COLUMN "icons" jsonb;--> statement-breakpoint
ALTER TABLE "versions" ADD COLUMN "manifest_version" text DEFAULT '1.9.0' NOT NULL;